### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by ducdetronquito** [ducdetronquito/requestz#8]
> So the idea is use system library and make https feature optional, See https://curl.se/docs/ssl-compared.html
> I suggest to use Schannel under windows since it is no c dependencs, and use openssl for linux, Secure Transport for macOS
Cf: https://old.reddit.com/r/Zig/comments/ju1hud/requestz_http_client_for_zig/gc91lks/

**Comment by GrooveStomp** [comment]
Hey, nice project!
I wrote my own Zig HTTP client. I don't think it's as comprehensive as yours, but it does support HTTPS via GnuTLS on Linux.
I can share that code with you if you're interested.
I guess if you run into any issues with OpenSSL then it might be interesting for you.

**Comment by ducdetronquito** [comment]
Hi @GrooveStomp !

Thank you ! Yes I am definitely interested :)
Do you have a repository ?

**Comment by GrooveStomp** [comment]
Yeah, I just created one to share with you: https://git.sr.ht/~groovestomp/zig-tls-demo/tree

**Comment by ducdetronquito** [comment]
Thanks a lot, I will have a deeper look at it in the upcoming weeks :)

**Comment by QuixoticValentine** [comment]
I'd like to +1 this as a feature, Requestz has the easiest interface of any zig HTTP client thus far, HTTPS support would be awesome (As somebody who wants an easy to use HTTPS lib).

**Comment by ducdetronquito** [comment]
Hi @QuixoticValentine,

Thanks for the kind words !

I have taken some time off these past weeks, but I will start to work again on h11/requestz in the following days.
HTTPS is definitely on my TODO list for 2021 :)

**Comment by ducdetronquito** [comment]
Time flies...

Chunked transfer encoding is looks usable; it only needs some testing.
I think I will be able to start working on HTTPS in the following weeks but no promise ^^"

PS: First, I intend to make if work with [iguanaTLS](https://github.com/alexnask/iguanaTLS)

**Comment by ducdetronquito** [comment]
Hey !

I think I finally managed to make HTTPS works with [iguanaTLS](https://github.com/alexnask/iguanaTLS) !
It is very lightly tested right now, so expect it to break. It if does break, I will be very happy if you could open an issue about it :)
