### ISSUE TITLE
MIT, BSD, ... or EUPL

### ISSUE THREAD

**Issue by P-E-SCHMITZ** [ducdetronquito/requestz#9]
Hating the copyright law red tape is something human (especially for non-lawyers) and you have both my comprehension and sympathy.
Since pure public domain is not practised in Europe, the use of the permissive MIT license seems to be the most recommended in such case.  
Whithout all the legal red tape, permissive licences like MIT or BSD are simple, but they are not reciprocal (some say "copyleft"). So, do not be upset if someone (i.e. one of the GAFA companies) copy all your source code and redistribute it under their own proprietary terms.  The advantage of a reciprocal license is that it forces people that redistribute your source code, even modified or improved, to provide it back to you under the same original license. This is the case of the famous GPL-3.0 which is long, complex, poorly interoperable and incompatible with other licences. An alternative is indeed the use of the EUPL, valid in 23 languages, which is in addition "interoperable" (freedom and no conditions for linking with different software) and more "compatible" (possibility to redistribute the covered source code under other similar outbound licenses listed as "compatible" in its appendix).

**Comment by ducdetronquito** [comment]
Hi @P-E-SCHMITZ,

Thanks for the advice about this complex topic !

To avoid having duplicated issues, would you mind to re-post your comment on this existing issue -->#7 ?

Have a nice day :)
